name: CI Caller

on:
  push:
    branches: [ "main", "dev", "staging", "hotfix-add-CI" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  # Se Invoca el flujo reutilizable del repo central
  call-java-pipeline:
    permissions:      # <--- Se añaden los permisos lectura/escritura para acceso de repo central
      checks: write
      pull-requests: write
      contents: write
    uses: ecno20/devops-library/.github/workflows/java-build.yml@main
    with:
      java-version: '17'
    # Próximamente agregaré los secretos (GCP_PROJECT_ID), aquí